import.meta.glob(['../images/**', '../fonts/**']);
import '../css/app.css';

import { accordion } from './accordion.js';
import { burger } from './burger.js';
import { changePricesTabs } from './changePricesTabs.js';
import { initBlogsFilter } from './filters/filterBlogs.js';
import { initDoctorsFilter } from './filters/filterDoctors.js';
import { initWorksFilter } from './filters/filterWorks.js';
import { initForms } from './forms.js';
import { scrollMap } from './map.js';
import './modals.js';
import { scrollCertificates } from './sliders/scrollCertificates.js';
import { scrollGallery } from './sliders/scrollGallery.js';
import { scrollOffers } from './sliders/scrollOffers.js';
import { scrollReviews } from './sliders/scrollReviews.js';
import { scrollServicesImages } from './sliders/scrollServicesGallery.js';
import { scrollToTop } from './sliders/scrollToTop.js';
import { scrollWorks } from './sliders/scrollWorks.js';
document.addEventListener('DOMContentLoaded', () => {
    burger();
    accordion();
    scrollReviews();
    scrollWorks();
    scrollGallery();
    scrollToTop();
    scrollMap();
    scrollServicesImages();
    scrollCertificates();
    scrollOffers();
    initForms();
    changePricesTabs();
    initDoctorsFilter();
    initBlogsFilter();
    initWorksFilter();
});
